name: cb-pipelinet
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.16"
          cache: false
      - name: install golang ci lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
      - name: golangci-lint
        run: golangci-lint run -c ./circuit-breaker/.golangci.yml ./circuit-breaker/... -v
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Install dependencies
        run: go work sync
      - name: run tests
        run: go test ./circuit-breaker/... -v -p 1 -race
