name: db-pipelinet
on:
  push:
    paths:
      - "db/*"
    branches:
      - main
  pull_request:
    paths:
      - "db/*"
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  run-commitlint-on-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1
      - name: install commitlint
        run: npm install -g @commitlint/config-conventional
      - name: configure commitlint rule
        run: >
          echo "{ extends: ['@commitlint/config-conventional'] }" > .commitlintrc
      - name: Validate all commits from PR
        run: echo ${{ github.event.head_commit.message }} | npx commitlint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go work sync
      - name: run tests
        run: go test ./db/... -v -p 1 -race
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go work sync
      - name: run tests
        run: go test ./db/... -v -p 1 -race
