name: db-pipelinet
on:
  push:
    paths:
      - "db/*"
    branches:
      - main
  pull_request:
    paths:
      - "db/*"
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go work sync
      - name: run tests
        run: go test ./db/... -v -p 1 -race
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go work sync
      - name: run tests
        run: go test ./db/... -v -p 1 -race
