name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        run: golangci-lint run -c .golangci.yml $(go list -f '{{.Dir}}'/... -m | xargs) -v
