name: log-pipelinet
on:
  push:
    paths:
      - "log/*"
    branches:
      - main
  pull_request:
    paths:
      - "log/*"
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: install golang ci lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
      - name: golangci-lint version
        run: golangci-lint version
      - name: golangci-lint
        run: golangci-lint run -c ./log/.golangci.yml ./log/... -v
